[theme]
base = "light"
primaryColor = "#28407A"
backgroundColor = "#EEF1F3"
secondaryBackgroundColor = "#E2E8EE"
textColor = "#141A22"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"